#!/usr/bin/env zsh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# debugging
# yabai -m config debug_output on

# UNMANAGED="yabai/centerUnmanaged.sh"

# global settings
yabai -m config window_origin_display           default
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off # keep floating windows at the top
yabai -m config window_shadow                   off
yabai -m config window_opacity                  on
# yabai -m config window_opacity_duration         200000.0
# yabai -m config active_window_opacity           0.95
# yabai -m config normal_window_opacity           0.95
yabai -m config active_window_opacity           1.00
yabai -m config normal_window_opacity           1.00
yabai -m config insert_feedback_color           0xffFDAEAB

# new window treatment
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    on

# mouse options
yabai -m config mouse_follows_focus             off
yabai -m config focus_follows_mouse             autofocus
yabai -m config mouse_modifier                  alt
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize
yabai -m config mouse_drop_action               stack

# general space settings
yabai -m config layout                          bsp
yabai -m config external_bar                    all:16:0
yabai -m config top_padding                     32
yabai -m config bottom_padding                  16
yabai -m config left_padding                    18
yabai -m config right_padding                   18
yabai -m config window_gap                      16

# $UNMANAGED

# yabai -m signal --add event=system_woke action="brew services restart sketchybar"

# scratch space configuration
# Create scratch space (space 11) if it doesn't exist
yabai -m space 11 --create 2>/dev/null || true
# Set scratch space to float layout for better temporary window management
yabai -m space 11 --layout float

# Display management - automatically move spaces 6-10 to second display when connected
yabai -m signal --add event=display_added action="$HOME/.config/sketchybar/plugins/display_manager.sh"
yabai -m signal --add event=display_removed action="$HOME/.config/sketchybar/plugins/display_manager.sh"
yabai -m signal --add event=display_changed action="$HOME/.config/sketchybar/plugins/display_manager.sh"

# Run display manager on startup to set initial state
$HOME/.config/sketchybar/plugins/display_manager.sh

# Window rules
yabai -m rule --add app="^mpv$" manage=off
yabai -m rule --add app="^Preview$" manage=off grid=4:4:1:1:2:2

# start janky boarders
borders active_color=0xff625A60 inactive_color=0xff2d2a2e width=4.0 &

yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'
